# Generated by Django 6.0 on 2025-12-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforma', '0002_alter_post_img_alter_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='son',
            field=models.IntegerField(default=0),
        ),
    ]
