# Generated by Django 6.0 on 2025-12-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforma', '0003_post_son'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='son',
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(),
        ),
    ]
