# Generated by Django 6.0 on 2026-01-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforma', '0004_remove_post_son_alter_post_img_alter_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text3',
            field=models.IntegerField(null=True),
        ),
    ]
