# Generated by Django 5.2.8 on 2026-02-16 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforma', '0005_post_text2_post_text3'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkmateUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
